# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-2047906d3d734eb798fbba451d5fc6c9
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-2047906d3d734eb798fbba451d5fc6c9
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: https://codegen-0311-1392800598.cos.ap-shanghai.myqcloud.com
    secretId: AKID2we8RYTBh097sSpz2veAWTJSTJxSp10m
    secretKey: c0CICtRmxvfCWfbMvJSO8f1A51vfEjCX
    region: ap-shanghai
    bucket: codegen-0311-1392800598